import type { JournalEntry } from './studio';
import type { MoneyEvent } from './types';

/** Old journals grouped billing under `sale`. Preserve IDs while recovering their meaning. */
export function journalMoneyKind(entry: JournalEntry): MoneyEvent['kind'] | undefined {
  if (entry.kind !== 'sale') return;
  if (entry.moneyKind) return entry.moneyKind;
  // Only recognize titles previously generated by the bridge, not words inside descriptions.
  const title = entry.title.split(' · ')[0].trim().toLowerCase();
  const legacy: Record<string, MoneyEvent['kind']> = {
    cancelled: 'churned', expired: 'expired', 'billing issue': 'failed', 'trial started': 'trial_started',
    'subscription started': 'subscription_started', 'subscription pending': 'subscription_pending',
    'subscription resumed': 'subscription_resumed', subscribed: 'subscribed', dispute: 'dispute', refund: 'refund',
  };
  return legacy[title] ?? (entry.amount ? entry.amount > 0 ? 'sale' : 'refund' : 'subscription_pending');
}
export function isCashEvent(event: Pick<MoneyEvent, 'kind' | 'amount'>) {
  return Number.isFinite(event.amount) && event.amount !== 0 && ['sale', 'subscribed', 'subscription_started', 'refund', 'dispute'].includes(event.kind);
}
export function journalCategory(entry: JournalEntry) {
  if (entry.kind !== 'sale') return entry.kind;
  return isCashEvent({kind:journalMoneyKind(entry)!, amount:entry.amount ?? 0}) ? 'sale' : 'subscription';
}
export const billingLabel = (kind: MoneyEvent['kind']) => ({
  sale: 'Payment', refund: 'Refund', dispute: 'Dispute', failed: 'Billing issue', churned: 'Subscription cancelled',
  expired: 'Subscription expired', trial_started: 'Trial started', subscribed: 'New subscriber',
  subscription_started: 'Subscription started', subscription_pending: 'Subscription pending', subscription_resumed: 'Subscription resumed',
})[kind];
